---
name: CI

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  check-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: 'go.mod'

      - name: Check for go vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -test ./...

  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Run golangci-lint (Golang Linter)
        uses: golangci/golangci-lint-action@v3

  unit-tests:
    needs: [check-vulnerabilities, golang-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: 'go.mod'

      - name: Run Tests
        run: go test ./...

  end2end-linux:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: 'go.mod'

      - name: Build application
        run: go build

      - name: Run End2End Tests
        run: ./test/end2end/linux.bash

  end2end-windows:
    needs: unit-tests
    runs-on: windows-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: 'go.mod'

      - name: Build application
        run: go build

      - name: Run End2End Tests
        run: ./test/end2end/windows.ps1
