---
name: _Get Tag Id

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    outputs:
      tag_id:
        description: 'The Id of the passed Tag'
        value: ${{ jobs.get-tag-id.outputs.tag_id }}
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  get-tag-id:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.tag-id.outputs.tag_id }}
    steps:
      - name: Get Tag Id
        id: tag-id
        run: |
          resp=$(curl -i -X GET "https://api.github.com/repos/${{ github.repository }}/releases" \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}")

          header=$(echo "${resp}" | sed '/^\r$/q' | tr -d '\r\n')
          body=$(echo "${resp}" | sed -n '/^\r$/,${p}' | sed '1d' | tr -d '\r\n')
          if ! grep -q "HTTP/2 200" <<< "${header}"; then
            echo "received non HTTP status code 200: ${body}"
            exit 1
          fi

          echo "tag_id"=$(echo "${body}" | jq -r ".[] | select(.tag_name == \"${{ inputs.tag }}\") | .id") >> $GITHUB_OUTPUT
